version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: dev
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run:
          name: Install
          command: npm install
          working_directory: gatsby
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Gatsby build site
          command: npm build
          working_directory: gatsby
      - run:
          name: ls
          command: ls
          working_directory: gatsby
      - run:
          name: echo
          command: echo $CIRCLE_WORKING_DIRECTORY