version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: dev
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run:
          name: Install
          command: npm install
          working_directory: gatsby
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Gatsby build site
          command: npm run build
          working_directory: gatsby
      - run:
          name: ls
          command: ls
          working_directory: gatsby
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: deploy
          command: echo ' deploy successful'
          working_directory: gatsby
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  
       
