version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: dev
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run:
          name: Install
          command: npm install
          working_directory: gatsby
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Gatsby build site
          command: npm run build
          working_directory: gatsby
      - persist_to_workspace:
          root: gatsby/public
          paths:
            - '*'
      - run:
          name: ls
          command: ls
          working_directory: gatsby
  deploy:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    steps:
      - checkout
      - attach_workspace:
          at: gatsby/workspace  
      - run:
          name: ls
          command: ls
      - run:
          name: ls workspace
          command: ls gatsby/workspace
      - run:
          name: Install deploy dependencies
          command: |
            npm install -g gh-pages
            git config user.email "deepa.ann.john1@gmail.com"
            git config user.name "deepaannjohn"
      - run:
          name: Deploy docs to master branch
          command: gh-pages -d gatsby/workspace -b master -e .
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  
       
